from django import forms
from .models import (
    Recipe,
    FamilyPreference,
    MealPlan,
    MealPlannerPreferences,
    DietaryRestriction
)
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class RecipeForm(forms.ModelForm):
    class Meta:
        model = Recipe
        fields = [
            'title',
            'author',
            'description',
            'ingredients',
            'steps',
            'notes',
            'is_ai_generated',
            'tags'
        ]
        widgets = {
            'description': forms.Textarea(attrs={'rows': 4, 'cols': 40}),
            'ingredients': forms.Textarea(attrs={'rows': 4, 'cols': 40}),
            'steps': forms.Textarea(attrs={'rows': 4, 'cols': 40}),
            'notes': forms.Textarea(attrs={'rows': 2, 'cols': 40}),
            'tags': forms.CheckboxSelectMultiple()
        }
        labels = {
            'title': 'Recipe Title',
            'author': 'Author Name',
            'description': 'Description',
            'ingredients': 'Ingredients',
            'steps': 'Cooking Steps',
            'notes': 'Additional Notes',
            'is_ai_generated': 'Is AI Generated?',
        }
        help_texts = {
            'title': 'Enter the title of the recipe.',
            'author': 'Enter the name of the author (optional).',
            'description': 'Provide a brief description of the recipe.',
            'ingredients': 'List all ingredients required for the recipe.',
            'steps': 'Describe the steps to prepare the recipe.',
            'notes': 'Any additional notes or tips for this recipe.',
            'is_ai_generated': 'Check if this recipe was generated by AI.',
        }
        error_messages = {
            'title': {
                'max_length': "This title is too long.",
            },
            'ingredients': {
                'required': "Ingredients are required.",
            },
            'steps': {
                'required': "Cooking steps are required.",
            },
        }

class MealPlanForm(forms.ModelForm):
    recipe = forms.ModelChoiceField(queryset=Recipe.objects.none())  # Correctly define the field

    class Meta:
        model = MealPlan
        fields = ['date', 'meal_type', 'recipe']

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)
        if user:
            # Filter recipes by the logged-in user
            self.fields['recipe'].queryset = Recipe.objects.filter(user=user) # type: ignore

class FamilyPreferenceForm(forms.ModelForm):
    class Meta:
        model = FamilyPreference
        fields = ['family_member', 'preference']
        widgets = {
            'family_member': forms.TextInput(attrs={'placeholder': 'e.g. Nina'}),
            'preference': forms.Select
        }
        labels = {
            'family_member': 'Family Member',
            'preference': 'Preference Level',
        }
        help_texts = {
            'family_member': 'Enter the name of the family member.',
            'preference': 'Select the preference level for this recipe.',
        }
        error_messages = {
            'family_member': {
                'required': "Family member name is required.",
            },
            'preference': {
                'required': "Preference level is required.",
            },
        }

class CustomUserCreationForm(UserCreationForm):
    email = forms.EmailField(required=True, widget=forms.EmailInput(attrs={'class': 'form-control'}))

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")


class MealPlannerPreferencesForm(forms.ModelForm):
    """Form for configuring smart meal planner preferences"""

    class Meta:
        model = MealPlannerPreferences
        fields = [
            'max_weeknight_time',
            'max_weekend_time',
            'avoid_repeat_days',
            'variety_score',
            'dietary_restrictions',
            'vegetarian_meals_per_week',
            'use_leftovers',
            'batch_cooking_friendly',
        ]
        widgets = {
            'max_weeknight_time': forms.NumberInput(attrs={
                'class': 'form-control',
                'min': '15',
                'max': '120',
                'step': '5'
            }),
            'max_weekend_time': forms.NumberInput(attrs={
                'class': 'form-control',
                'min': '30',
                'max': '240',
                'step': '15'
            }),
            'avoid_repeat_days': forms.NumberInput(attrs={
                'class': 'form-control',
                'min': '7',
                'max': '90',
                'step': '7'
            }),
            'variety_score': forms.NumberInput(attrs={
                'class': 'form-control',
                'min': '1',
                'max': '10',
                'step': '1'
            }),
            'dietary_restrictions': forms.CheckboxSelectMultiple(),
            'vegetarian_meals_per_week': forms.NumberInput(attrs={
                'class': 'form-control',
                'min': '0',
                'max': '7',
                'step': '1'
            }),
            'use_leftovers': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
            'batch_cooking_friendly': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
        }
        labels = {
            'max_weeknight_time': 'Max Weeknight Cooking Time (minutes)',
            'max_weekend_time': 'Max Weekend Cooking Time (minutes)',
            'avoid_repeat_days': 'Don\'t Repeat Recipes Within (days)',
            'variety_score': 'Variety Preference (1=Similar, 10=Very Diverse)',
            'dietary_restrictions': 'Dietary Restrictions',
            'vegetarian_meals_per_week': 'Minimum Vegetarian Meals Per Week',
            'use_leftovers': 'Plan for Using Leftovers',
            'batch_cooking_friendly': 'Prefer Meal-Prep Friendly Recipes',
        }
        help_texts = {
            'max_weeknight_time': 'Maximum time you want to spend cooking on weeknights',
            'max_weekend_time': 'Maximum time you want to spend cooking on weekends',
            'avoid_repeat_days': 'How long before the same recipe can be suggested again',
            'variety_score': 'Higher scores mean more variety in your meal plan',
            'vegetarian_meals_per_week': 'Ensure at least this many vegetarian meals each week',
        }


class WeeklyPlanGeneratorForm(forms.Form):
    """Form for generating a weekly meal plan"""

    week_start = forms.DateField(
        required=False,
        widget=forms.DateInput(attrs={
            'type': 'date',
            'class': 'form-control'
        }),
        help_text='Leave blank to start from next Monday'
    )

    meals_to_plan = forms.MultipleChoiceField(
        choices=[
            ('breakfast', 'Breakfast'),
            ('lunch', 'Lunch'),
            ('dinner', 'Dinner'),
        ],
        initial=['dinner'],
        widget=forms.CheckboxSelectMultiple(),
        help_text='Select which meals you want to plan'
    )




