from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from .models import (
    MealPlan,
    MealPlannerPreferences,
    Recipe,
)


class RecipeForm(forms.ModelForm):
    class Meta:
        model = Recipe
        fields = ["title", "author", "description", "ingredients_text", "steps", "notes", "is_ai_generated", "tags"]
        widgets = {
            "description": forms.Textarea(attrs={"rows": 4, "cols": 40}),
            "ingredients_text": forms.Textarea(attrs={"rows": 4, "cols": 40}),
            "steps": forms.Textarea(attrs={"rows": 4, "cols": 40}),
            "notes": forms.Textarea(attrs={"rows": 2, "cols": 40}),
            "tags": forms.CheckboxSelectMultiple(),
        }
        labels = {
            "title": "Recipe Title",
            "author": "Author Name",
            "description": "Description",
            "ingredients_text": "Ingredients",
            "steps": "Cooking Steps",
            "notes": "Additional Notes",
            "is_ai_generated": "Is AI Generated?",
        }
        help_texts = {
            "title": "Enter the title of the recipe.",
            "author": "Enter the name of the author (optional).",
            "description": "Provide a brief description of the recipe.",
            "ingredients_text": "List all ingredients required for the recipe.",
            "steps": "Describe the steps to prepare the recipe.",
            "notes": "Any additional notes or tips for this recipe.",
            "is_ai_generated": "Check if this recipe was generated by AI.",
        }
        error_messages = {
            "title": {
                "max_length": "This title is too long.",
            },
            "ingredients_text": {
                "required": "Ingredients are required.",
            },
            "steps": {
                "required": "Cooking steps are required.",
            },
        }


class MealPlanForm(forms.ModelForm):
    recipe = forms.ModelChoiceField(queryset=Recipe.objects.none())  # Correctly define the field

    class Meta:
        model = MealPlan
        fields = ["date", "meal_type", "recipe"]

    def __init__(self, *args, **kwargs):
        user = kwargs.pop("user", None)
        super().__init__(*args, **kwargs)
        if user:
            # Filter recipes by the logged-in user
            self.fields["recipe"].queryset = Recipe.objects.filter(user=user)  # type: ignore


class CustomUserCreationForm(UserCreationForm):
    email = forms.EmailField(required=True, widget=forms.EmailInput(attrs={"class": "form-control"}))

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")


class MealPlannerPreferencesForm(forms.ModelForm):
    """Form for configuring smart meal planner preferences"""

    class Meta:
        model = MealPlannerPreferences
        fields = [
            "max_weeknight_time",
            "max_weekend_time",
            "avoid_repeat_days",
            "reminder_time",
        ]
        widgets = {
            "max_weeknight_time": forms.NumberInput(
                attrs={"class": "form-control", "min": "15", "max": "120", "step": "5"}
            ),
            "max_weekend_time": forms.NumberInput(
                attrs={"class": "form-control", "min": "30", "max": "240", "step": "15"}
            ),
            "avoid_repeat_days": forms.NumberInput(
                attrs={"class": "form-control", "min": "7", "max": "90", "step": "7"}
            ),
            "reminder_time": forms.TimeInput(attrs={"class": "form-control", "type": "time"}),
        }
        labels = {
            "max_weeknight_time": "Max Weeknight Cooking Time (minutes)",
            "max_weekend_time": "Max Weekend Cooking Time (minutes)",
            "avoid_repeat_days": "Don't Repeat Recipes Within (days)",
            "reminder_time": "Dinner Reminder Time",
        }
        help_texts = {
            "max_weeknight_time": "Maximum time you want to spend cooking on weeknights",
            "max_weekend_time": "Maximum time you want to spend cooking on weekends",
            "avoid_repeat_days": "How long before the same recipe can be suggested again",
            "reminder_time": "When to send a daily push notification for tonight's dinner",
        }


class WeeklyPlanGeneratorForm(forms.Form):
    """Form for generating a weekly meal plan"""

    week_start = forms.DateField(
        required=False,
        widget=forms.DateInput(attrs={"type": "date", "class": "form-control"}),
        help_text="Leave blank to start from next Monday",
    )

    meals_to_plan = forms.MultipleChoiceField(
        choices=[
            ("breakfast", "Breakfast"),
            ("lunch", "Lunch"),
            ("dinner", "Dinner"),
        ],
        initial=["dinner"],
        widget=forms.CheckboxSelectMultiple(),
        help_text="Select which meals you want to plan",
    )
