from django import forms
from .models import Recipe
class RecipeForm(forms.ModelForm):
    class Meta:
        model = Recipe
        fields = [
            'title',
            'author',
            'description',
            'ingredients',
            'steps',
            'notes',
            'is_ai_generated'
        ]
        widgets = {
            'ingredients': forms.Textarea(attrs={'rows': 4, 'cols': 40}),
            'steps': forms.Textarea(attrs={'rows': 4, 'cols': 40}),
            'notes': forms.Textarea(attrs={'rows': 2, 'cols': 40}),
        }
        labels = {
            'title': 'Recipe Title',
            'author': 'Author Name',
            'description': 'Description',
            'ingredients': 'Ingredients',
            'steps': 'Cooking Steps',
            'notes': 'Additional Notes',
            'is_ai_generated': 'Is AI Generated?',
        }
        help_texts = {
            'title': 'Enter the title of the recipe.',
            'author': 'Enter the name of the author (optional).',
            'description': 'Provide a brief description of the recipe.',
            'ingredients': 'List all ingredients required for the recipe.',
            'steps': 'Describe the steps to prepare the recipe.',
            'notes': 'Any additional notes or tips for this recipe.',
            'is_ai_generated': 'Check if this recipe was generated by AI.',
        }
        error_messages = {
            'title': {
                'max_length': "This title is too long.",
            },
            'ingredients': {
                'required': "Ingredients are required.",
            },
            'steps': {
                'required': "Cooking steps are required.",
            },
        }
