# Generated by Django 5.2.4 on 2025-10-21 11:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0007_familypreference_user_mealplan_user_recipe_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mealplan",
            options={"ordering": ["date", "meal_type"]},
        ),
        migrations.AlterModelOptions(
            name="recipe",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="recipe",
            name="cook_time",
            field=models.PositiveIntegerField(
                blank=True, help_text="Cooking time in minutes", null=True
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="difficulty",
            field=models.CharField(
                blank=True,
                choices=[("easy", "Easy"), ("medium", "Medium"), ("hard", "Hard")],
                default="medium",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="recipes/"),
        ),
        migrations.AddField(
            model_name="recipe",
            name="prep_time",
            field=models.PositiveIntegerField(
                blank=True, help_text="Preparation time in minutes", null=True
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="servings",
            field=models.PositiveIntegerField(
                default=1, help_text="Number of servings"
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name="familypreference",
            unique_together={("user", "family_member", "recipe")},
        ),
        migrations.AddIndex(
            model_name="mealplan",
            index=models.Index(
                fields=["user", "date"], name="recipes_mea_user_id_1c29da_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mealplan",
            index=models.Index(
                fields=["user", "date", "meal_type"],
                name="recipes_mea_user_id_71aaf5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="recipe",
            index=models.Index(
                fields=["-created_at"], name="recipes_rec_created_57db65_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recipe",
            index=models.Index(
                fields=["user", "-created_at"], name="recipes_rec_user_id_142c3e_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="familypreference",
            constraint=models.CheckConstraint(
                check=models.Q(("preference__in", [1, 2, 3])),
                name="preference_valid_value",
            ),
        ),
    ]
