# Generated by Django 5.2.4 on 2025-10-21 12:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0008_alter_mealplan_options_alter_recipe_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="mealplan",
            unique_together={("user", "date", "meal_type")},
        ),
    ]
