# Generated by Django 5.2.4 on 2025-10-21 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0009_alter_mealplan_unique_together"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DietaryRestriction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="GeneratedMealPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week_start", models.DateField()),
                ("week_end", models.DateField()),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("approved", models.BooleanField(default=False)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "overall_happiness_score",
                    models.DecimalField(
                        decimal_places=1,
                        help_text="Predicted family satisfaction (0-100)",
                        max_digits=4,
                        null=True,
                    ),
                ),
                (
                    "variety_score",
                    models.DecimalField(
                        decimal_places=1,
                        help_text="Recipe variety score (0-100)",
                        max_digits=4,
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-generated_at"],
            },
        ),
        migrations.CreateModel(
            name="GeneratedMealPlanEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "meal_type",
                    models.CharField(
                        choices=[
                            ("breakfast", "Breakfast"),
                            ("lunch", "Lunch"),
                            ("dinner", "Dinner"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "happiness_score",
                    models.DecimalField(
                        decimal_places=1,
                        help_text="Predicted satisfaction for this meal (0-100)",
                        max_digits=4,
                        null=True,
                    ),
                ),
                ("is_leftover", models.BooleanField(default=False)),
                (
                    "leftover_from",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generates_leftovers",
                        to="recipes.generatedmealplanentry",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="recipes.generatedmealplan",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="recipes.recipe"
                    ),
                ),
            ],
            options={
                "ordering": ["date", "meal_type"],
            },
        ),
        migrations.CreateModel(
            name="MealPlannerPreferences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "max_weeknight_time",
                    models.IntegerField(
                        default=45,
                        help_text="Maximum cooking time for weeknights (minutes)",
                    ),
                ),
                (
                    "max_weekend_time",
                    models.IntegerField(
                        default=90,
                        help_text="Maximum cooking time for weekends (minutes)",
                    ),
                ),
                (
                    "avoid_repeat_days",
                    models.IntegerField(
                        default=14,
                        help_text="Don't repeat recipes within this many days",
                    ),
                ),
                (
                    "variety_score",
                    models.IntegerField(
                        default=7, help_text="Higher = more variety (1-10)"
                    ),
                ),
                (
                    "vegetarian_meals_per_week",
                    models.IntegerField(
                        default=0, help_text="Minimum vegetarian meals per week"
                    ),
                ),
                (
                    "use_leftovers",
                    models.BooleanField(
                        default=True, help_text="Plan for using leftovers"
                    ),
                ),
                (
                    "batch_cooking_friendly",
                    models.BooleanField(
                        default=False,
                        help_text="Prefer recipes that work well for meal prep",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dietary_restrictions",
                    models.ManyToManyField(blank=True, to="recipes.dietaryrestriction"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="planner_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Meal planner preferences",
            },
        ),
        migrations.CreateModel(
            name="RecipeCookingHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cooked_date", models.DateField()),
                (
                    "meal_type",
                    models.CharField(
                        choices=[
                            ("breakfast", "Breakfast"),
                            ("lunch", "Lunch"),
                            ("dinner", "Dinner"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "⭐"),
                            (2, "⭐⭐"),
                            (3, "⭐⭐⭐"),
                            (4, "⭐⭐⭐⭐"),
                            (5, "⭐⭐⭐⭐⭐"),
                        ],
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cooking_history",
                        to="recipes.recipe",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cooking_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Recipe cooking histories",
                "ordering": ["-cooked_date"],
            },
        ),
        migrations.AddIndex(
            model_name="generatedmealplan",
            index=models.Index(
                fields=["user", "-generated_at"], name="recipes_gen_user_id_db0c1c_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="generatedmealplanentry",
            unique_together={("plan", "date", "meal_type")},
        ),
        migrations.AddIndex(
            model_name="recipecookinghistory",
            index=models.Index(
                fields=["user", "-cooked_date"], name="recipes_rec_user_id_a84965_idx"
            ),
        ),
    ]
