# Generated by Django 4.2.29 on 2026-03-28 04:40
# Manually adjusted to work around Django 4.2 + Python 3.13 SQLite introspection bug.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("recipes", "0010_dietaryrestriction_generatedmealplan_and_more"),
    ]

    operations = [
        # -------------------------------------------------------
        # 1. Create new models
        # -------------------------------------------------------
        migrations.CreateModel(
            name="CookingNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cooked_date", models.DateField()),
                (
                    "rating",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        null=True,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                ("would_make_again", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-cooked_date"],
            },
        ),
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("produce", "Produce"),
                            ("dairy", "Dairy"),
                            ("meat", "Meat"),
                            ("pantry", "Pantry"),
                            ("spices", "Spices"),
                            ("frozen", "Frozen"),
                            ("bakery", "Bakery"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="RecipeIngredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "---"),
                            ("tsp", "teaspoon"),
                            ("tbsp", "tablespoon"),
                            ("cup", "cup"),
                            ("ml", "millilitre"),
                            ("l", "litre"),
                            ("g", "gram"),
                            ("kg", "kilogram"),
                            ("oz", "ounce"),
                            ("lb", "pound"),
                            ("piece", "piece"),
                            ("slice", "slice"),
                            ("pinch", "pinch"),
                            ("handful", "handful"),
                            ("bunch", "bunch"),
                            ("can", "can"),
                            ("clove", "clove"),
                        ],
                        max_length=10,
                    ),
                ),
                ("preparation_notes", models.CharField(blank=True, max_length=100)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipe_ingredients",
                        to="recipes.ingredient",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ShoppingListItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("checked", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shopping_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["checked", "created_at"],
            },
        ),
        # -------------------------------------------------------
        # 2. Drop removed models using raw SQL to avoid SQLite
        #    introspection bugs with AlterUniqueTogether on Py 3.13
        # -------------------------------------------------------
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS recipes_generatedmealplanentry;",
            reverse_sql=migrations.RunSQL.noop,
            state_operations=[
                migrations.AlterUniqueTogether(
                    name="generatedmealplanentry",
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name="generatedmealplanentry",
                    name="leftover_from",
                ),
                migrations.RemoveField(
                    model_name="generatedmealplanentry",
                    name="plan",
                ),
                migrations.RemoveField(
                    model_name="generatedmealplanentry",
                    name="recipe",
                ),
                migrations.DeleteModel(
                    name="GeneratedMealPlanEntry",
                ),
            ],
        ),
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS recipes_generatedmealplan;",
            reverse_sql=migrations.RunSQL.noop,
            state_operations=[
                migrations.RemoveField(
                    model_name="generatedmealplan",
                    name="user",
                ),
                migrations.DeleteModel(
                    name="GeneratedMealPlan",
                ),
            ],
        ),
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS recipes_familypreference;",
            reverse_sql=migrations.RunSQL.noop,
            state_operations=[
                migrations.AlterUniqueTogether(
                    name="familypreference",
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name="familypreference",
                    name="recipe",
                ),
                migrations.RemoveField(
                    model_name="familypreference",
                    name="user",
                ),
                migrations.DeleteModel(
                    name="FamilyPreference",
                ),
            ],
        ),
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS recipes_recipecookinghistory;",
            reverse_sql=migrations.RunSQL.noop,
            state_operations=[
                migrations.RemoveField(
                    model_name="recipecookinghistory",
                    name="recipe",
                ),
                migrations.RemoveField(
                    model_name="recipecookinghistory",
                    name="user",
                ),
                migrations.DeleteModel(
                    name="RecipeCookingHistory",
                ),
            ],
        ),
        # -------------------------------------------------------
        # 3. Remove dietary_restrictions M2M before dropping model
        # -------------------------------------------------------
        migrations.RemoveField(
            model_name="mealplannerpreferences",
            name="dietary_restrictions",
        ),
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS recipes_dietaryrestriction;",
            reverse_sql=migrations.RunSQL.noop,
            state_operations=[
                migrations.DeleteModel(
                    name="DietaryRestriction",
                ),
            ],
        ),
        # -------------------------------------------------------
        # 4. Slim down MealPlannerPreferences
        # -------------------------------------------------------
        migrations.RemoveField(
            model_name="mealplannerpreferences",
            name="batch_cooking_friendly",
        ),
        migrations.RemoveField(
            model_name="mealplannerpreferences",
            name="use_leftovers",
        ),
        migrations.RemoveField(
            model_name="mealplannerpreferences",
            name="variety_score",
        ),
        migrations.RemoveField(
            model_name="mealplannerpreferences",
            name="vegetarian_meals_per_week",
        ),
        # -------------------------------------------------------
        # 5. Recipe field changes
        # -------------------------------------------------------
        migrations.RenameField(
            model_name="recipe",
            old_name="ingredients",
            new_name="ingredients_text",
        ),
        migrations.AlterField(
            model_name="recipe",
            name="ingredients_text",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="cooking_mode_steps",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="source",
            field=models.CharField(
                choices=[
                    ("manual", "Manual"),
                    ("ai", "AI Generated"),
                    ("url", "Imported from URL"),
                    ("family", "Family Recipe"),
                ],
                default="manual",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="servings",
            field=models.PositiveIntegerField(
                default=4, help_text="Number of servings"
            ),
        ),
        # -------------------------------------------------------
        # 6. Other field additions
        # -------------------------------------------------------
        migrations.AddField(
            model_name="mealplan",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="tag",
            name="tag_type",
            field=models.CharField(
                choices=[
                    ("dietary", "Dietary"),
                    ("cuisine", "Cuisine"),
                    ("method", "Method"),
                    ("time", "Time"),
                ],
                default="cuisine",
                max_length=10,
            ),
        ),
        # -------------------------------------------------------
        # 7. Add FK fields to new models and indexes
        # -------------------------------------------------------
        migrations.AddField(
            model_name="recipeingredient",
            name="recipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipe_ingredients",
                to="recipes.recipe",
            ),
        ),
        migrations.AddField(
            model_name="cookingnote",
            name="recipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cooking_notes",
                to="recipes.recipe",
            ),
        ),
        migrations.AddField(
            model_name="cookingnote",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cooking_notes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="cookingnote",
            index=models.Index(
                fields=["user", "-cooked_date"], name="recipes_coo_user_id_1a62cf_idx"
            ),
        ),
    ]
