# Generated by Django 4.2.29 on 2026-03-28 21:10

from django.db import migrations


def populate_households(apps, schema_editor):
    """For each User, create a Household and HouseholdMembership, then
    assign household and added_by to all MealPlan and ShoppingListItem rows."""
    User = apps.get_model("auth", "User")
    Household = apps.get_model("recipes", "Household")
    HouseholdMembership = apps.get_model("recipes", "HouseholdMembership")
    MealPlan = apps.get_model("recipes", "MealPlan")
    ShoppingListItem = apps.get_model("recipes", "ShoppingListItem")

    from recipes.models.household import generate_household_code

    for user in User.objects.all():
        household = Household.objects.create(
            name=f"{user.username}'s Kitchen",
            code=generate_household_code(),
            created_by=user,
        )
        HouseholdMembership.objects.create(
            user=user,
            household=household,
        )
        MealPlan.objects.filter(user=user).update(
            household=household,
            added_by=user,
        )
        ShoppingListItem.objects.filter(user=user).update(
            household=household,
            added_by=user,
        )


def reverse_populate(apps, schema_editor):
    """Reverse: delete all households and memberships."""
    Household = apps.get_model("recipes", "Household")
    Household.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0013_add_household_fields"),
    ]

    operations = [
        migrations.RunPython(populate_households, reverse_populate),
    ]
