# Generated by Django 4.2.29 on 2026-03-28 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_populate_households'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='mealplan',
            name='recipes_mea_user_id_1c29da_idx',
        ),
        migrations.RemoveIndex(
            model_name='mealplan',
            name='recipes_mea_user_id_71aaf5_idx',
        ),
        migrations.AlterUniqueTogether(
            name='mealplan',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='shoppinglistitem',
            name='user',
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='household',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_plans', to='recipes.household'),
        ),
        migrations.AlterField(
            model_name='shoppinglistitem',
            name='household',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_items', to='recipes.household'),
        ),
        migrations.AlterUniqueTogether(
            name='mealplan',
            unique_together={('household', 'date', 'meal_type')},
        ),
        migrations.AddIndex(
            model_name='mealplan',
            index=models.Index(fields=['household', 'date'], name='recipes_mea_househo_ce8d4f_idx'),
        ),
        migrations.AddIndex(
            model_name='mealplan',
            index=models.Index(fields=['household', 'date', 'meal_type'], name='recipes_mea_househo_d1bbf2_idx'),
        ),
        migrations.RemoveField(
            model_name='mealplan',
            name='user',
        ),
    ]
