# Generated by Django 4.2.29 on 2026-03-28 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0015_remove_user_fks"),
    ]

    operations = [
        migrations.AddField(
            model_name="shoppinglistitem",
            name="category",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="shoppinglistitem",
            name="is_generated",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="shoppinglistitem",
            name="quantity",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="shoppinglistitem",
            name="recipe_sources",
            field=models.CharField(blank=True, help_text="Comma-separated recipe names", max_length=500),
        ),
    ]
