# Generated by Django 5.2.12 on 2026-03-29 06:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0016_add_shopping_item_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="daycomment",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="mealplan",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="daycomment",
            constraint=models.UniqueConstraint(fields=("household", "user", "date"), name="unique_household_user_date"),
        ),
        migrations.AddConstraint(
            model_name="mealplan",
            constraint=models.UniqueConstraint(
                fields=("household", "date", "meal_type"),
                name="unique_household_date_meal",
            ),
        ),
    ]
