# Generated by Django 5.2.12 on 2026-03-30 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0019_mealplantemplate_mealplantemplateentry"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="image_url",
            field=models.URLField(
                blank=True,
                help_text="External image URL (e.g. Unsplash)",
                max_length=500,
            ),
        ),
    ]
