# Generated by Django 5.2.12 on 2026-04-01

from django.db import migrations


UNIT_NORMALIZE = {
    "cloves": "clove", "grams": "g", "gram": "g", "kilograms": "kg",
    "kilogram": "kg", "milliliters": "ml", "millilitres": "ml",
    "milliliter": "ml", "millilitre": "ml", "liters": "l", "litres": "l",
    "liter": "l", "litre": "l", "teaspoon": "tsp", "teaspoons": "tsp",
    "tablespoon": "tbsp", "tablespoons": "tbsp", "cups": "cup",
    "ounces": "oz", "ounce": "oz", "pounds": "lb", "pound": "lb",
    "pieces": "piece", "slices": "slice", "pinches": "pinch",
    "handfuls": "handful", "bunches": "bunch", "cans": "can",
    "whole": "piece", "medium": "piece", "large": "piece", "small": "piece",
    "stalks": "piece", "stalk": "piece", "heads": "piece", "head": "piece",
    "sprigs": "bunch", "sprig": "bunch",
}

VALID_UNITS = {"", "tsp", "tbsp", "cup", "ml", "l", "g", "kg", "oz", "lb",
               "piece", "slice", "pinch", "handful", "bunch", "can", "clove"}


def fix_units(apps, schema_editor):
    RecipeIngredient = apps.get_model("recipes", "RecipeIngredient")
    Ingredient = apps.get_model("recipes", "Ingredient")

    # Fix invalid units
    fixed = 0
    for ri in RecipeIngredient.objects.all():
        if ri.unit and ri.unit not in VALID_UNITS:
            old = ri.unit
            normalized = UNIT_NORMALIZE.get(ri.unit.lower().strip(), "")
            if normalized != ri.unit:
                ri.unit = normalized
                ri.save(update_fields=["unit"])
                fixed += 1

    # Remove blank-name ingredients
    blank = Ingredient.objects.filter(name="")
    if blank.exists():
        RecipeIngredient.objects.filter(ingredient__name="").delete()
        blank.delete()

    print(f"Fixed {fixed} ingredient units")


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0020_add_recipe_image_url"),
    ]

    operations = [
        migrations.RunPython(fix_units, migrations.RunPython.noop),
    ]
