# Generated by Django 5.2.12 on 2026-04-03 00:34

from django.db import migrations


VALID_CATEGORIES = {"produce", "dairy", "meat", "pantry", "spices", "frozen", "bakery", "other"}

CATEGORY_ALIASES = {
    "vegetable": "produce",
    "vegetables": "produce",
    "fruit": "produce",
    "fruits": "produce",
    "grain": "pantry",
    "grains": "pantry",
    "pasta": "pantry",
    "noodle": "pantry",
    "noodles": "pantry",
    "rice": "pantry",
    "sauce": "pantry",
    "sauces": "pantry",
    "condiment": "pantry",
    "condiments": "pantry",
    "oil": "pantry",
    "oils": "pantry",
    "seasoning": "spices",
    "seasonings": "spices",
    "spice": "spices",
    "herb": "spices",
    "herbs": "spices",
    "protein": "meat",
    "poultry": "meat",
    "seafood": "meat",
    "fish": "meat",
    "bread": "bakery",
    "cheese": "dairy",
    "milk": "dairy",
    "egg": "dairy",
    "eggs": "dairy",
}


def fix_categories(apps, schema_editor):
    Ingredient = apps.get_model("recipes", "Ingredient")
    fixed = 0
    for ingredient in Ingredient.objects.all():
        cat = ingredient.category.lower().strip() if ingredient.category else ""
        if cat not in VALID_CATEGORIES:
            new_cat = CATEGORY_ALIASES.get(cat, "other")
            ingredient.category = new_cat
            ingredient.save(update_fields=["category"])
            fixed += 1
    print(f"Fixed {fixed} ingredient categories")


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0021_fix_ingredient_units"),
    ]

    operations = [
        migrations.RunPython(fix_categories, migrations.RunPython.noop),
    ]
